---
- name: Install Docker and run Nginx container
  hosts: all
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Pull Nginx container image
      docker_image:
        name: nginx
        state: present

    - name: Start Nginx container
      docker_container:
        name: nginx
        image: nginx
        ports:
          - "80:80"
        state: started
